// <auto-generated />
using BombaAustra.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BombaAustra.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BombaAustra.Shared.Entities.Compañia", b =>
                {
                    b.Property<int>("ID_COMPAÑIA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_COMPAÑIA"));

                    b.HasKey("ID_COMPAÑIA");

                    b.HasIndex("ID_COMPAÑIA")
                        .IsUnique();

                    b.ToTable("COMPANIAS");
                });

            modelBuilder.Entity("BombaAustra.Shared.Entities.Equipo", b =>
                {
                    b.Property<int>("ID_EQUIPO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_EQUIPO"));

                    b.HasKey("ID_EQUIPO");

                    b.HasIndex("ID_EQUIPO")
                        .IsUnique();

                    b.ToTable("EQUIPOS");
                });

            modelBuilder.Entity("BombaAustra.Shared.Entities.EstadoEquipo", b =>
                {
                    b.Property<int>("ID_ESTADO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_ESTADO"));

                    b.HasKey("ID_ESTADO");

                    b.HasIndex("ID_ESTADO")
                        .IsUnique();

                    b.ToTable("ESTADO_EQUIPO");
                });

            modelBuilder.Entity("BombaAustra.Shared.Entities.NombreCompañia", b =>
                {
                    b.Property<int>("ID_NOMBRE_COMPAÑIA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_NOMBRE_COMPAÑIA"));

                    b.HasKey("ID_NOMBRE_COMPAÑIA");

                    b.HasIndex("ID_NOMBRE_COMPAÑIA")
                        .IsUnique();

                    b.ToTable("NOMBRE_COMPANIAS");
                });

            modelBuilder.Entity("BombaAustra.Shared.Entities.Reporte", b =>
                {
                    b.Property<int>("ID_REPORTE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_REPORTE"));

                    b.HasKey("ID_REPORTE");

                    b.HasIndex("ID_REPORTE")
                        .IsUnique();

                    b.ToTable("REPORTES");
                });

            modelBuilder.Entity("BombaAustra.Shared.Entities.TipoEquipo", b =>
                {
                    b.Property<int>("ID_TIPO_EQUIPO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_TIPO_EQUIPO"));

                    b.HasKey("ID_TIPO_EQUIPO");

                    b.HasIndex("ID_TIPO_EQUIPO")
                        .IsUnique();

                    b.ToTable("TIPO_EQUIPO");
                });

            modelBuilder.Entity("BombaAustra.Shared.Entities.TipoUsuario", b =>
                {
                    b.Property<int>("ID_TIPO_USUARIO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_TIPO_USUARIO"));

                    b.HasKey("ID_TIPO_USUARIO");

                    b.HasIndex("ID_TIPO_USUARIO")
                        .IsUnique();

                    b.ToTable("TIPO_USUARIOS");
                });

            modelBuilder.Entity("BombaAustra.Shared.Entities.Usuario", b =>
                {
                    b.Property<string>("ID_RUT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("APELLIDO_M")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("APELLIDO_P")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DV_RUT")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("NOMBRE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TIPO_USUARIOS")
                        .HasColumnType("int");

                    b.HasKey("ID_RUT");

                    b.HasIndex("ID_RUT")
                        .IsUnique();

                    b.ToTable("USUARIOS");
                });
#pragma warning restore 612, 618
        }
    }
}
